version: '3'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on: 
            - db

    db:
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: 'blog'
            MYSQL_ROOT_PASSWORD: '09109242665@Am'
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306